name: Android Release

# 1
on:
  # 2
  push:
    branches: [ "main" ]
# 3
jobs:
  # 4
  build:
    # 5
    runs-on: ubuntu-latest

    # 6
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.7'
          channel: 'stable'
      - run: flutter --version
      # 7
      - name: Get dependencies
        run: flutter pub get

      # Runs a set of commands using the runners shell
      - name: Start release build
        run: flutter build appbundle
