name: Android Release

# 1
on:
  # 2
  push:
    branches: [ "main" ]
# 3
jobs:
  # 4
  build:
    # 5
    runs-on: ubuntu-latest

    # 6
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
      - uses: dart-lang/setup-dart@9a04e6d73cca37bd455e0608d7e5092f881fd603
        with:
          flutter-version: '3.10.1'
          channel: 'stable'
          version: 3.10.1
      - run: flutter --version
      # 7
      - name: Get dependencies
        run: flutter pub get

      # Runs a set of commands using the runners shell
      - name: Start release build
        run: flutter build appbundle
